export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  MINISTRY_ADMIN = 'MINISTRY_ADMIN',
  MINISTRY_OFFICER = 'MINISTRY_OFFICER',
  DATA_ADMIN = 'DATA_ADMIN',
  PROVINCIAL_ADMIN = 'PROVINCIAL_ADMIN',
  DISTRICT_ADMIN = 'DISTRICT_ADMIN',
  HOSPITAL_ADMIN = 'HOSPITAL_ADMIN',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  HEALTH_WORKER = 'HEALTH_WORKER',
  PHARMACIST = 'PHARMACIST',
  CITIZEN = 'CITIZEN',
}

export enum HospitalType {
  GENERAL = 'GENERAL',
  TEACHING = 'TEACHING',
  SPECIALIZED = 'SPECIALIZED',
  DISTRICT = 'DISTRICT',
  PROVINCIAL = 'PROVINCIAL',
  PRIVATE = 'PRIVATE',
  CLINIC = 'CLINIC',
}

export enum HospitalStatus {
  OPERATIONAL = 'OPERATIONAL',
  PARTIAL = 'PARTIAL',
  EMERGENCY_ONLY = 'EMERGENCY_ONLY',
  CLOSED = 'CLOSED',
}

export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum AppointmentType {
  CONSULTATION = 'CONSULTATION',
  FOLLOW_UP = 'FOLLOW_UP',
  EMERGENCY = 'EMERGENCY',
  ROUTINE = 'ROUTINE',
  SPECIALIST = 'SPECIALIST',
}

export enum ReferralPriority {
  NORMAL = 'NORMAL',
  URGENT = 'URGENT',
  CRITICAL = 'CRITICAL',
}

export enum ReferralStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum MedicineStatus {
  AVAILABLE = 'AVAILABLE',
  LOW_STOCK = 'LOW_STOCK',
  CRITICAL = 'CRITICAL',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  EXPIRED = 'EXPIRED',
}

export enum AlertLevel {
  GREEN = 'GREEN',
  YELLOW = 'YELLOW',
  ORANGE = 'ORANGE',
  RED = 'RED',
}

export enum EmergencySeverity {
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum EmergencyStatus {
  ACTIVE = 'ACTIVE',
  RESPONDING = 'RESPONDING',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum ComplaintStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum ComplaintPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum AnnouncementCategory {
  MINISTRY_NOTICE = 'MINISTRY_NOTICE',
  PUBLIC_HEALTH_ALERT = 'PUBLIC_HEALTH_ALERT',
  POLICY_UPDATE = 'POLICY_UPDATE',
  EMERGENCY_NOTICE = 'EMERGENCY_NOTICE',
  CAMPAIGN = 'CAMPAIGN',
  GENERAL = 'GENERAL',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AuditAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_REGISTER = 'USER_REGISTER',
  PATIENT_ACCESS = 'PATIENT_ACCESS',
  PATIENT_CREATE = 'PATIENT_CREATE',
  PATIENT_UPDATE = 'PATIENT_UPDATE',
  APPOINTMENT_CREATE = 'APPOINTMENT_CREATE',
  APPOINTMENT_UPDATE = 'APPOINTMENT_UPDATE',
  REFERRAL_CREATE = 'REFERRAL_CREATE',
  REFERRAL_UPDATE = 'REFERRAL_UPDATE',
  MEDICINE_UPDATE = 'MEDICINE_UPDATE',
  EMERGENCY_CREATE = 'EMERGENCY_CREATE',
  EMERGENCY_UPDATE = 'EMERGENCY_UPDATE',
  ANNOUNCEMENT_PUBLISH = 'ANNOUNCEMENT_PUBLISH',
  HOSPITAL_CREATE = 'HOSPITAL_CREATE',
  HOSPITAL_UPDATE = 'HOSPITAL_UPDATE',
  ADMIN_ACTION = 'ADMIN_ACTION',
}

export enum SriLankaRegion {
  WESTERN = 'WESTERN',
  CENTRAL = 'CENTRAL',
  SOUTHERN = 'SOUTHERN',
  NORTHERN = 'NORTHERN',
  EASTERN = 'EASTERN',
  NORTH_WESTERN = 'NORTH_WESTERN',
  NORTH_CENTRAL = 'NORTH_CENTRAL',
  UVA = 'UVA',
  SABARAGAMUWA = 'SABARAGAMUWA',
}
