export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  MINISTRY_ADMIN = 'MINISTRY_ADMIN',
  MINISTRY_OFFICER = 'MINISTRY_OFFICER',
  DATA_ADMIN = 'DATA_ADMIN',
  PROVINCIAL_ADMIN = 'PROVINCIAL_ADMIN',
  DISTRICT_ADMIN = 'DISTRICT_ADMIN',
  HOSPITAL_ADMIN = 'HOSPITAL_ADMIN',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  HEALTH_WORKER = 'HEALTH_WORKER',
  PHARMACIST = 'PHARMACIST',
  CITIZEN = 'CITIZEN',
}

export enum HospitalType {
  GENERAL = 'GENERAL',
  TEACHING = 'TEACHING',
  SPECIALIZED = 'SPECIALIZED',
  DISTRICT = 'DISTRICT',
  PROVINCIAL = 'PROVINCIAL',
  PRIVATE = 'PRIVATE',
  CLINIC = 'CLINIC',
}

export enum HospitalStatus {
  OPERATIONAL = 'OPERATIONAL',
  PARTIAL = 'PARTIAL',
  EMERGENCY_ONLY = 'EMERGENCY_ONLY',
  CLOSED = 'CLOSED',
}

export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum AppointmentType {
  CONSULTATION = 'CONSULTATION',
  FOLLOW_UP = 'FOLLOW_UP',
  EMERGENCY = 'EMERGENCY',
  ROUTINE = 'ROUTINE',
  SPECIALIST = 'SPECIALIST',
}

export enum ReferralPriority {
  NORMAL = 'NORMAL',
  URGENT = 'URGENT',
  CRITICAL = 'CRITICAL',
}

export enum ReferralStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum MedicineStatus {
  AVAILABLE = 'AVAILABLE',
  LOW_STOCK = 'LOW_STOCK',
  CRITICAL = 'CRITICAL',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  EXPIRED = 'EXPIRED',
  UNKNOWN = 'UNKNOWN', // No current inventory data — honest state
}

export enum AlertLevel {
  GREEN = 'GREEN',
  YELLOW = 'YELLOW',
  ORANGE = 'ORANGE',
  RED = 'RED',
}

export enum EmergencySeverity {
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum EmergencyStatus {
  ACTIVE = 'ACTIVE',
  RESPONDING = 'RESPONDING',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum ComplaintStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum ComplaintPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum AnnouncementCategory {
  MINISTRY_NOTICE = 'MINISTRY_NOTICE',
  PUBLIC_HEALTH_ALERT = 'PUBLIC_HEALTH_ALERT',
  POLICY_UPDATE = 'POLICY_UPDATE',
  EMERGENCY_NOTICE = 'EMERGENCY_NOTICE',
  CAMPAIGN = 'CAMPAIGN',
  GENERAL = 'GENERAL',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AuditAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_REGISTER = 'USER_REGISTER',
  PATIENT_ACCESS = 'PATIENT_ACCESS',
  PATIENT_CREATE = 'PATIENT_CREATE',
  PATIENT_UPDATE = 'PATIENT_UPDATE',
  APPOINTMENT_CREATE = 'APPOINTMENT_CREATE',
  APPOINTMENT_UPDATE = 'APPOINTMENT_UPDATE',
  REFERRAL_CREATE = 'REFERRAL_CREATE',
  REFERRAL_UPDATE = 'REFERRAL_UPDATE',
  MEDICINE_UPDATE = 'MEDICINE_UPDATE',
  EMERGENCY_CREATE = 'EMERGENCY_CREATE',
  EMERGENCY_UPDATE = 'EMERGENCY_UPDATE',
  ANNOUNCEMENT_PUBLISH = 'ANNOUNCEMENT_PUBLISH',
  HOSPITAL_CREATE = 'HOSPITAL_CREATE',
  HOSPITAL_UPDATE = 'HOSPITAL_UPDATE',
  HOSPITAL_IMPORT = 'HOSPITAL_IMPORT',
  ADMIN_ACTION = 'ADMIN_ACTION',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  OTP_SENT = 'OTP_SENT',
  OTP_VERIFICATION_FAILED = 'OTP_VERIFICATION_FAILED',
  OTP_VERIFIED = 'OTP_VERIFIED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  PASSWORD_RESET_RATE_LIMITED = 'PASSWORD_RESET_RATE_LIMITED',
  // Inventory
  INVENTORY_UPDATE = 'INVENTORY_UPDATE',
  INVENTORY_CREATE = 'INVENTORY_CREATE',
  INVENTORY_DELETE = 'INVENTORY_DELETE',
  // Queue
  QUEUE_TOKEN_CREATE = 'QUEUE_TOKEN_CREATE',
  QUEUE_TOKEN_UPDATE = 'QUEUE_TOKEN_UPDATE',
  // Practitioner
  PRACTITIONER_CREATE = 'PRACTITIONER_CREATE',
  PRACTITIONER_VERIFY = 'PRACTITIONER_VERIFY',
  PRACTITIONER_UPDATE = 'PRACTITIONER_UPDATE',
  STAFF_ASSIGNMENT_CREATE = 'STAFF_ASSIGNMENT_CREATE',
  STAFF_ASSIGNMENT_UPDATE = 'STAFF_ASSIGNMENT_UPDATE',
  // Data quality
  DATA_CORRECTION_SUBMIT = 'DATA_CORRECTION_SUBMIT',
  DATA_CORRECTION_RESOLVE = 'DATA_CORRECTION_RESOLVE',
  DATA_SOURCE_CREATE = 'DATA_SOURCE_CREATE',
  // Service availability
  SERVICE_AVAILABILITY_UPDATE = 'SERVICE_AVAILABILITY_UPDATE',
}

export enum SriLankaRegion {
  WESTERN = 'WESTERN',
  CENTRAL = 'CENTRAL',
  SOUTHERN = 'SOUTHERN',
  NORTHERN = 'NORTHERN',
  EASTERN = 'EASTERN',
  NORTH_WESTERN = 'NORTH_WESTERN',
  NORTH_CENTRAL = 'NORTH_CENTRAL',
  UVA = 'UVA',
  SABARAGAMUWA = 'SABARAGAMUWA',
}

// ── New enums for the Sri Lanka healthcare upgrade ────────────────────────────

export enum VerificationStatus {
  VERIFIED = 'VERIFIED',       // Confirmed against authoritative source
  PENDING = 'PENDING',         // Awaiting verification
  HISTORICAL = 'HISTORICAL',   // Data from a past report; may be outdated
  UNVERIFIED = 'UNVERIFIED',   // Source unknown or not validated
}

export enum ServiceAvailabilityStatus {
  AVAILABLE = 'AVAILABLE',
  SCHEDULED = 'SCHEDULED',
  TEMPORARILY_UNAVAILABLE = 'TEMPORARILY_UNAVAILABLE',
  UNKNOWN = 'UNKNOWN', // No current status information — never fabricated
}

export enum QueueStatus {
  BOOKED = 'BOOKED',
  CHECKED_IN = 'CHECKED_IN',
  WAITING = 'WAITING',
  CALLED = 'CALLED',
  IN_SERVICE = 'IN_SERVICE',
  COMPLETED = 'COMPLETED',
  MISSED = 'MISSED',
  CANCELLED = 'CANCELLED',
}

/**
 * Freshness of medicine inventory data.
 * Thresholds are configurable per hospital / deployment policy.
 * Defaults: CURRENT <30min, RECENT <4h, TODAY <24h, STALE >=24h
 */
export enum FreshnessStatus {
  CURRENT = 'CURRENT',
  RECENT = 'RECENT',
  TODAY = 'TODAY',
  STALE = 'STALE',
  UNKNOWN = 'UNKNOWN', // No update timestamp available
}

export enum DataSourceType {
  OFFICIAL_GOVERNMENT = 'OFFICIAL_GOVERNMENT',
  REGULATOR = 'REGULATOR',
  AUTHORIZED_HOSPITAL = 'AUTHORIZED_HOSPITAL',
  AUTHORIZED_PROVINCIAL = 'AUTHORIZED_PROVINCIAL',
  USER_SUBMITTED = 'USER_SUBMITTED',
  SYSTEM_CALCULATED = 'SYSTEM_CALCULATED',
}

/** Sri Lanka Medical Council practitioner registration status */
export enum SlmcRegistrationStatus {
  ACTIVE = 'ACTIVE',
  LAPSED = 'LAPSED',
  CANCELLED = 'CANCELLED',
  UNKNOWN = 'UNKNOWN',
}

/** Crowd level derived from actual queue data — never fabricated */
export enum CrowdLevel {
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  BUSY = 'BUSY',
  VERY_BUSY = 'VERY_BUSY',
  UNKNOWN = 'UNKNOWN',
}

export enum DataCorrectionStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED_AGAINST_SOURCE = 'VERIFIED_AGAINST_SOURCE',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
