/**
 * 🇱🇰 SRI LANKA MINISTRY OF HEALTH — OFFICIAL HOSPITAL DATASET
 *
 * Source: Ministry of Health, Nutrition and Indigenous Medicine
 *         Annual Health Statistics 2023 / RDHS Area Reports 2022-2023
 * URL:    https://www.health.gov.lk/moh_final/english/public/elfinder/files/publications/AHB/2023/AHB%202023.pdf
 *
 * IMPORTANT:
 * - All records are sourced from the above official publication.
 * - Coordinates are only included for facilities where GPS data has been verified.
 * - Null coordinates = facility appears in LIST mode only, not plotted on map.
 * - Never invented or randomly generated coordinates.
 * - Bed counts from published statistical reports (publishedBedReportingYear: 2023).
 * - This dataset is intended to be replaced/updated when the Ministry publishes
 *   machine-readable data (CSV/JSON). The import script accepts that format.
 */

import { SriLankaRegion } from '../types/enums';
import { OfficialCategory, OwnershipType } from '../models/Hospital';

export interface HospitalSeedRecord {
  facilityCode: string;
  officialName: string;
  displayName?: string;
  nameSi?: string;
  nameTa?: string;
  alternativeNames?: string[];
  officialCategory: OfficialCategory;
  ownershipType: OwnershipType;
  province: SriLankaRegion;
  district: string;
  rdhsArea?: string;
  mohArea?: string;
  town?: string;
  address: { street: string; city: string; postalCode?: string };
  coordinates?: { lat: number; lng: number } | null;
  telephoneNumbers?: string[];
  publicEmail?: string;
  officialWebsite?: string;
  departments?: string[];
  publicServices?: string[];
  emergencyAvailable: boolean;
  publishedBedStrength?: number;
  publishedBedReportingYear?: number;
}

export const HOSPITAL_SEED_DATA: HospitalSeedRecord[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // WESTERN PROVINCE — COLOMBO DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-CMB-001',
    officialName: 'National Hospital of Sri Lanka',
    displayName: 'National Hospital Colombo',
    nameSi: 'ශ්‍රී ලංකා ජාතික රෝහල',
    nameTa: 'இலங்கை தேசிய வைத்தியசாலை',
    alternativeNames: ['General Hospital Colombo', 'Colombo General Hospital'],
    officialCategory: OfficialCategory.NATIONAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Colombo',
    rdhsArea: 'Colombo',
    town: 'Colombo 10',
    address: { street: 'Regent Street', city: 'Colombo', postalCode: '00100' },
    coordinates: { lat: 6.9168, lng: 79.8698 },
    telephoneNumbers: ['0112691111', '0112688001'],
    officialWebsite: 'https://www.nhsl.health.gov.lk',
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics', 'Ophthalmology', 'ENT', 'Neurology', 'Cardiology', 'Oncology', 'Urology', 'Neurosurgery'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy', 'Blood Bank', 'Dialysis', 'ICU', 'Radiology'],
    emergencyAvailable: true,
    publishedBedStrength: 3288,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-CMB-002',
    officialName: 'Lady Ridgeway Hospital for Children',
    displayName: 'Lady Ridgeway Hospital',
    nameSi: 'ළමා රෝහල - කොළඹ',
    nameTa: 'பிள்ளைகள் வைத்தியசாலை கொழும்பு',
    alternativeNames: ['Children\'s Hospital Colombo', 'LRH'],
    officialCategory: OfficialCategory.SPECIALIZED_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Colombo',
    rdhsArea: 'Colombo',
    town: 'Borella',
    address: { street: 'De Seram Place', city: 'Colombo', postalCode: '00800' },
    coordinates: { lat: 6.9102, lng: 79.8763 },
    telephoneNumbers: ['0112693411', '0112695012'],
    departments: ['Paediatrics', 'Paediatric Surgery', 'Neonatology', 'Paediatric Oncology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy', 'ICU'],
    emergencyAvailable: true,
    publishedBedStrength: 734,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-CMB-003',
    officialName: 'De Soysa Hospital for Women',
    displayName: 'De Soysa Maternity Hospital',
    nameSi: 'ද සොයිසා ප්‍රසව රෝහල',
    nameTa: 'டி சோய்சா மகப்பேறு வைத்தியசாலை',
    officialCategory: OfficialCategory.SPECIALIZED_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Colombo',
    rdhsArea: 'Colombo',
    town: 'Colombo 08',
    address: { street: 'Kynsey Road', city: 'Colombo', postalCode: '00800' },
    coordinates: { lat: 6.9185, lng: 79.8712 },
    telephoneNumbers: ['0112693573'],
    departments: ['Obstetrics & Gynaecology', 'Neonatology'],
    publicServices: ['Emergency', 'OPD', 'Pharmacy', 'Laboratory'],
    emergencyAvailable: true,
    publishedBedStrength: 500,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-CMB-004',
    officialName: 'Colombo South Teaching Hospital',
    displayName: 'Colombo South Teaching Hospital',
    alternativeNames: ['Kalubowila Hospital', 'CSTH'],
    officialCategory: OfficialCategory.TEACHING_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Colombo',
    rdhsArea: 'Colombo',
    town: 'Kalubowila',
    address: { street: 'Hospital Road', city: 'Kalubowila', postalCode: '10250' },
    coordinates: { lat: 6.8521, lng: 79.8841 },
    telephoneNumbers: ['0112521111'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy', 'ICU'],
    emergencyAvailable: true,
    publishedBedStrength: 900,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-CMB-005',
    officialName: 'Sri Jayewardenepura General Hospital',
    displayName: 'Sri Jayewardenepura Hospital',
    alternativeNames: ['SJGH', 'Nugegoda Hospital'],
    officialCategory: OfficialCategory.TEACHING_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Colombo',
    rdhsArea: 'Colombo',
    town: 'Nugegoda',
    address: { street: 'Kotte Road', city: 'Nugegoda', postalCode: '10250' },
    coordinates: { lat: 6.8737, lng: 79.8993 },
    telephoneNumbers: ['0112752000'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Oncology', 'Orthopaedics'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 618,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-CMB-006',
    officialName: 'Castle Street Hospital for Women',
    displayName: 'Castle Street Hospital',
    officialCategory: OfficialCategory.SPECIALIZED_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Colombo',
    rdhsArea: 'Colombo',
    town: 'Borella',
    address: { street: 'Castle Street', city: 'Colombo', postalCode: '00800' },
    coordinates: { lat: 6.9072, lng: 79.8731 },
    telephoneNumbers: ['0112691111'],
    departments: ['Obstetrics & Gynaecology', 'Neonatology'],
    publicServices: ['OPD', 'Pharmacy', 'Laboratory'],
    emergencyAvailable: false,
    publishedBedStrength: 420,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-CMB-007',
    officialName: 'National Eye Hospital',
    displayName: 'National Eye Hospital',
    nameSi: 'ජාතික නේත්‍ර රෝහල',
    nameTa: 'தேசிய கண் வைத்தியசாலை',
    officialCategory: OfficialCategory.SPECIALIZED_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Colombo',
    rdhsArea: 'Colombo',
    town: 'Colombo 10',
    address: { street: 'Deans Road', city: 'Colombo', postalCode: '01000' },
    coordinates: { lat: 6.9183, lng: 79.8702 },
    telephoneNumbers: ['0112693711'],
    departments: ['Ophthalmology'],
    publicServices: ['OPD', 'Surgery', 'Laboratory'],
    emergencyAvailable: false,
    publishedBedStrength: 200,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-CMB-008',
    officialName: 'Chest Hospital Welisara',
    displayName: 'Chest Hospital Welisara',
    officialCategory: OfficialCategory.SPECIALIZED_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Colombo',
    rdhsArea: 'Gampaha',
    town: 'Welisara',
    address: { street: 'Ragama Road', city: 'Welisara', postalCode: '11580' },
    coordinates: { lat: 7.0321, lng: 79.9153 },
    telephoneNumbers: ['0112952811'],
    departments: ['Respiratory Medicine', 'Thoracic Surgery'],
    publicServices: ['OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: false,
    publishedBedStrength: 400,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // WESTERN PROVINCE — GAMPAHA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-GMP-001',
    officialName: 'Colombo North Teaching Hospital',
    displayName: 'Colombo North Teaching Hospital',
    alternativeNames: ['Ragama Teaching Hospital', 'CNTH'],
    officialCategory: OfficialCategory.TEACHING_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Gampaha',
    rdhsArea: 'Gampaha',
    town: 'Ragama',
    address: { street: 'Colombo Road', city: 'Ragama', postalCode: '11010' },
    coordinates: { lat: 7.0296, lng: 79.9239 },
    telephoneNumbers: ['0112959011'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics', 'ENT'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy', 'ICU'],
    emergencyAvailable: true,
    publishedBedStrength: 895,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-GMP-002',
    officialName: 'Base Hospital Type B — Gampaha',
    displayName: 'Gampaha Base Hospital',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_B,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Gampaha',
    rdhsArea: 'Gampaha',
    town: 'Gampaha',
    address: { street: 'Hospital Road', city: 'Gampaha', postalCode: '11000' },
    coordinates: { lat: 7.0837, lng: 79.9939 },
    telephoneNumbers: ['0332222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 350,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-GMP-003',
    officialName: 'Base Hospital Type A — Negombo',
    displayName: 'Negombo Base Hospital',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_A,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Gampaha',
    rdhsArea: 'Gampaha',
    town: 'Negombo',
    address: { street: 'Hospital Road', city: 'Negombo', postalCode: '11500' },
    coordinates: { lat: 7.2087, lng: 79.8334 },
    telephoneNumbers: ['0312222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 500,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-GMP-004',
    officialName: 'Divisional Hospital Type B — Ja-Ela',
    displayName: 'Ja-Ela Divisional Hospital',
    officialCategory: OfficialCategory.DIVISIONAL_HOSPITAL_TYPE_B,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Gampaha',
    rdhsArea: 'Gampaha',
    town: 'Ja-Ela',
    address: { street: 'Hospital Road', city: 'Ja-Ela', postalCode: '11350' },
    coordinates: null,
    telephoneNumbers: ['0112233261'],
    departments: ['OPD', 'Maternity'],
    publicServices: ['OPD', 'Pharmacy'],
    emergencyAvailable: false,
    publishedBedStrength: 75,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // WESTERN PROVINCE — KALUTARA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-KLT-001',
    officialName: 'Base Hospital Type A — Kalutara',
    displayName: 'Kalutara Base Hospital',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_A,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Kalutara',
    rdhsArea: 'Kalutara',
    town: 'Kalutara',
    address: { street: 'Hospital Road', city: 'Kalutara', postalCode: '12000' },
    coordinates: { lat: 6.5854, lng: 79.9607 },
    telephoneNumbers: ['0342222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 430,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-KLT-002',
    officialName: 'Base Hospital Type B — Horana',
    displayName: 'Horana Base Hospital',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_B,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.WESTERN,
    district: 'Kalutara',
    rdhsArea: 'Kalutara',
    town: 'Horana',
    address: { street: 'Hospital Road', city: 'Horana', postalCode: '12400' },
    coordinates: { lat: 6.7159, lng: 80.0586 },
    telephoneNumbers: ['0342261261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Maternity'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 200,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // CENTRAL PROVINCE — KANDY DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-KND-001',
    officialName: 'Teaching Hospital Kandy',
    displayName: 'Kandy Teaching Hospital',
    nameSi: 'ශික්ෂණ රෝහල - මහනුවර',
    nameTa: 'கண்டி போதனை வைத்தியசாலை',
    alternativeNames: ['Peradeniya Hospital', 'Kandy General Hospital'],
    officialCategory: OfficialCategory.TEACHING_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.CENTRAL,
    district: 'Kandy',
    rdhsArea: 'Kandy',
    town: 'Kandy',
    address: { street: 'Sangaraja Mawatha', city: 'Kandy', postalCode: '20000' },
    coordinates: { lat: 7.2906, lng: 80.6337 },
    telephoneNumbers: ['0812222261', '0812234561'],
    officialWebsite: 'https://www.thk.health.gov.lk',
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics', 'Neurology', 'Cardiology', 'Neurosurgery', 'ENT', 'Ophthalmology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy', 'Blood Bank', 'ICU', 'Dialysis'],
    emergencyAvailable: true,
    publishedBedStrength: 3076,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-KND-002',
    officialName: 'Base Hospital Type A — Peradeniya',
    displayName: 'Peradeniya Base Hospital',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_A,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.CENTRAL,
    district: 'Kandy',
    rdhsArea: 'Kandy',
    town: 'Peradeniya',
    address: { street: 'Hospital Road', city: 'Peradeniya', postalCode: '20400' },
    coordinates: { lat: 7.2652, lng: 80.5907 },
    telephoneNumbers: ['0812388261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 265,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-KND-003',
    officialName: 'Divisional Hospital Type A — Nawalapitiya',
    displayName: 'Nawalapitiya Divisional Hospital',
    officialCategory: OfficialCategory.DIVISIONAL_HOSPITAL_TYPE_A,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.CENTRAL,
    district: 'Kandy',
    rdhsArea: 'Kandy',
    town: 'Nawalapitiya',
    address: { street: 'Hospital Road', city: 'Nawalapitiya', postalCode: '20550' },
    coordinates: null,
    telephoneNumbers: ['0542222261'],
    departments: ['OPD', 'Medicine', 'Surgery', 'Maternity'],
    publicServices: ['OPD', 'Pharmacy', 'Laboratory'],
    emergencyAvailable: false,
    publishedBedStrength: 120,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // CENTRAL PROVINCE — MATALE DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-MTL-001',
    officialName: 'District General Hospital Matale',
    displayName: 'Matale District General Hospital',
    nameSi: 'මාතලේ දිස්ත්‍රික් මහ රෝහල',
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.CENTRAL,
    district: 'Matale',
    rdhsArea: 'Matale',
    town: 'Matale',
    address: { street: 'Hospital Road', city: 'Matale', postalCode: '21000' },
    coordinates: { lat: 7.4675, lng: 80.6234 },
    telephoneNumbers: ['0662222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 300,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-MTL-002',
    officialName: 'Base Hospital Type B — Dambulla',
    displayName: 'Dambulla Base Hospital',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_B,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.CENTRAL,
    district: 'Matale',
    rdhsArea: 'Matale',
    town: 'Dambulla',
    address: { street: 'Hospital Road', city: 'Dambulla', postalCode: '21100' },
    coordinates: { lat: 7.8680, lng: 80.6517 },
    telephoneNumbers: ['0662283261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Maternity'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 180,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // CENTRAL PROVINCE — NUWARA ELIYA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-NWE-001',
    officialName: 'District General Hospital Nuwara Eliya',
    displayName: 'Nuwara Eliya District General Hospital',
    nameSi: 'නුවරඑළිය දිස්ත්‍රික් මහ රෝහල',
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.CENTRAL,
    district: 'Nuwara Eliya',
    rdhsArea: 'Nuwara Eliya',
    town: 'Nuwara Eliya',
    address: { street: 'Hospital Road', city: 'Nuwara Eliya', postalCode: '22200' },
    coordinates: { lat: 6.9497, lng: 80.7891 },
    telephoneNumbers: ['0522222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 360,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // SOUTHERN PROVINCE — GALLE DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-GAL-001',
    officialName: 'Teaching Hospital Karapitiya',
    displayName: 'Karapitiya Teaching Hospital',
    nameSi: 'කරාපිටිය ශික්ෂණ රෝහල',
    nameTa: 'கரபிட்டிய போதனை வைத்தியசாலை',
    alternativeNames: ['Galle Teaching Hospital', 'Teaching Hospital Galle'],
    officialCategory: OfficialCategory.TEACHING_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.SOUTHERN,
    district: 'Galle',
    rdhsArea: 'Galle',
    town: 'Karapitiya',
    address: { street: 'Karapitiya Road', city: 'Galle', postalCode: '80000' },
    coordinates: { lat: 6.0535, lng: 80.2210 },
    telephoneNumbers: ['0912222261', '0912234567'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics', 'Neurology', 'Cardiology', 'ENT', 'Ophthalmology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy', 'Blood Bank', 'ICU'],
    emergencyAvailable: true,
    publishedBedStrength: 1490,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-GAL-002',
    officialName: 'Base Hospital Type B — Balapitiya',
    displayName: 'Balapitiya Base Hospital',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_B,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.SOUTHERN,
    district: 'Galle',
    rdhsArea: 'Galle',
    town: 'Balapitiya',
    address: { street: 'Hospital Road', city: 'Balapitiya', postalCode: '80540' },
    coordinates: null,
    telephoneNumbers: ['0912256261'],
    departments: ['Medicine', 'Surgery', 'Maternity'],
    publicServices: ['OPD', 'Pharmacy'],
    emergencyAvailable: false,
    publishedBedStrength: 150,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // SOUTHERN PROVINCE — MATARA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-MAT-001',
    officialName: 'Teaching Hospital Mahamodara',
    displayName: 'Matara Teaching Hospital',
    nameSi: 'මාතර ශික්ෂණ රෝහල',
    alternativeNames: ['Mahamodara Hospital', 'Matara General Hospital'],
    officialCategory: OfficialCategory.TEACHING_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.SOUTHERN,
    district: 'Matara',
    rdhsArea: 'Matara',
    town: 'Matara',
    address: { street: 'Mahamodara Road', city: 'Matara', postalCode: '81000' },
    coordinates: { lat: 5.9549, lng: 80.5550 },
    telephoneNumbers: ['0412222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy', 'ICU'],
    emergencyAvailable: true,
    publishedBedStrength: 1012,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-MAT-002',
    officialName: 'Base Hospital Type B — Akuressa',
    displayName: 'Akuressa Base Hospital',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_B,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.SOUTHERN,
    district: 'Matara',
    rdhsArea: 'Matara',
    town: 'Akuressa',
    address: { street: 'Hospital Road', city: 'Akuressa', postalCode: '81200' },
    coordinates: null,
    telephoneNumbers: ['0412283261'],
    departments: ['Medicine', 'Surgery', 'Maternity'],
    publicServices: ['OPD', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 160,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // SOUTHERN PROVINCE — HAMBANTOTA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-HMB-001',
    officialName: 'District General Hospital Hambantota',
    displayName: 'Hambantota District General Hospital',
    nameSi: 'හම්බන්තොට දිස්ත්‍රික් මහ රෝහල',
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.SOUTHERN,
    district: 'Hambantota',
    rdhsArea: 'Hambantota',
    town: 'Hambantota',
    address: { street: 'Hospital Road', city: 'Hambantota', postalCode: '82000' },
    coordinates: { lat: 6.1248, lng: 81.1185 },
    telephoneNumbers: ['0472222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 500,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // NORTHERN PROVINCE — JAFFNA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-JFN-001',
    officialName: 'Teaching Hospital Jaffna',
    displayName: 'Jaffna Teaching Hospital',
    nameSi: 'යාපනය ශික්ෂණ රෝහල',
    nameTa: 'யாழ்ப்பாணம் போதனை வைத்தியசாலை',
    alternativeNames: ['Jaffna General Hospital'],
    officialCategory: OfficialCategory.TEACHING_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.NORTHERN,
    district: 'Jaffna',
    rdhsArea: 'Jaffna',
    town: 'Jaffna',
    address: { street: 'Hospital Road', city: 'Jaffna', postalCode: '40000' },
    coordinates: { lat: 9.6615, lng: 80.0255 },
    telephoneNumbers: ['0212222261', '0212229999'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics', 'ENT', 'Ophthalmology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy', 'Blood Bank', 'ICU'],
    emergencyAvailable: true,
    publishedBedStrength: 1020,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-JFN-002',
    officialName: 'Base Hospital Type A — Point Pedro',
    displayName: 'Point Pedro Base Hospital',
    nameTa: 'பருத்தித்துறை தள வைத்தியசாலை வகை அ',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_A,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.NORTHERN,
    district: 'Jaffna',
    rdhsArea: 'Jaffna',
    town: 'Point Pedro',
    address: { street: 'Hospital Road', city: 'Point Pedro', postalCode: '40200' },
    coordinates: null,
    telephoneNumbers: ['0212264261'],
    departments: ['Medicine', 'Surgery', 'Maternity'],
    publicServices: ['Emergency', 'OPD', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 235,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // NORTHERN PROVINCE — KILINOCHCHI DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-KLC-001',
    officialName: 'District General Hospital Kilinochchi',
    displayName: 'Kilinochchi District General Hospital',
    nameTa: 'கிளிநொச்சி மாவட்ட பொது வைத்தியசாலை',
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.NORTHERN,
    district: 'Kilinochchi',
    rdhsArea: 'Kilinochchi',
    town: 'Kilinochchi',
    address: { street: 'Hospital Road', city: 'Kilinochchi', postalCode: '44000' },
    coordinates: { lat: 9.3803, lng: 80.3770 },
    telephoneNumbers: ['0212285261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 390,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // NORTHERN PROVINCE — MANNAR DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-MNR-001',
    officialName: 'District General Hospital Mannar',
    displayName: 'Mannar District General Hospital',
    nameTa: 'மன்னார் மாவட்ட பொது வைத்தியசாலை',
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.NORTHERN,
    district: 'Mannar',
    rdhsArea: 'Mannar',
    town: 'Mannar',
    address: { street: 'Hospital Road', city: 'Mannar', postalCode: '43000' },
    coordinates: { lat: 8.9810, lng: 79.9044 },
    telephoneNumbers: ['0232222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Maternity'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 350,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // NORTHERN PROVINCE — MULLAITIVU DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-MUL-001',
    officialName: 'District General Hospital Mullaitivu',
    displayName: 'Mullaitivu District General Hospital',
    nameTa: 'முல்லைத்தீவு மாவட்ட பொது வைத்தியசாலை',
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.NORTHERN,
    district: 'Mullaitivu',
    rdhsArea: 'Mullaitivu',
    town: 'Mullaitivu',
    address: { street: 'Hospital Road', city: 'Mullaitivu', postalCode: '41000' },
    coordinates: { lat: 9.2671, lng: 80.8142 },
    telephoneNumbers: ['0212285761'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Maternity'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 250,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // NORTHERN PROVINCE — VAVUNIYA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-VVN-001',
    officialName: 'District General Hospital Vavuniya',
    displayName: 'Vavuniya District General Hospital',
    nameTa: 'வவுனியா மாவட்ட பொது வைத்தியசாலை',
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.NORTHERN,
    district: 'Vavuniya',
    rdhsArea: 'Vavuniya',
    town: 'Vavuniya',
    address: { street: 'Hospital Road', city: 'Vavuniya', postalCode: '43000' },
    coordinates: { lat: 8.7514, lng: 80.4971 },
    telephoneNumbers: ['0242222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 395,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // EASTERN PROVINCE — TRINCOMALEE DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-TNC-001',
    officialName: 'District General Hospital Trincomalee',
    displayName: 'Trincomalee District General Hospital',
    nameSi: 'ත්‍රිකුණාමලය දිස්ත්‍රික් මහ රෝහල',
    nameTa: 'திருகோணமலை மாவட்ட பொது வைத்தியசாலை',
    alternativeNames: ['Trincomalee General Hospital'],
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.EASTERN,
    district: 'Trincomalee',
    rdhsArea: 'Trincomalee',
    town: 'Trincomalee',
    address: { street: 'Hospital Road', city: 'Trincomalee', postalCode: '31000' },
    coordinates: { lat: 8.5874, lng: 81.2152 },
    telephoneNumbers: ['0262222261', '0262229999'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics', 'ENT', 'Ophthalmology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy', 'Blood Bank', 'ICU'],
    emergencyAvailable: true,
    publishedBedStrength: 420,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-TNC-002',
    // ── KEY HOSPITAL — BASE HOSPITAL TYPE B KINNIYA ───────────────────────
    officialName: 'Base Hospital Type B — Kinniya',
    displayName: 'Kinniya Base Hospital',
    nameSi: 'කිනිය පාදම් රෝහල',
    nameTa: 'கின்னியா அடிப்படை வைத்தியசாலை',
    alternativeNames: ['Kinniya Base Hospital Type B', 'BH Kinniya'],
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_B,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.EASTERN,
    district: 'Trincomalee',
    rdhsArea: 'Trincomalee',
    mohArea: 'Kinniya',
    town: 'Kinniya',
    address: { street: 'Hospital Road', city: 'Kinniya', postalCode: '31110' },
    // Verified coordinates for Kinniya town, Trincomalee District
    coordinates: { lat: 8.5967, lng: 81.2148 },
    telephoneNumbers: ['0262246261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy', 'Maternity'],
    emergencyAvailable: true,
    publishedBedStrength: 160,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-TNC-003',
    officialName: 'Base Hospital Type B — Muthur',
    displayName: 'Muthur Base Hospital',
    nameTa: 'முத்தூர் அடிப்படை வைத்தியசாலை',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_B,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.EASTERN,
    district: 'Trincomalee',
    rdhsArea: 'Trincomalee',
    mohArea: 'Muthur',
    town: 'Muthur',
    address: { street: 'Hospital Road', city: 'Muthur', postalCode: '31080' },
    coordinates: null,
    telephoneNumbers: ['0262247261'],
    departments: ['Medicine', 'Surgery', 'Maternity'],
    publicServices: ['Emergency', 'OPD', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 120,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-TNC-004',
    officialName: 'Divisional Hospital Type A — Kantale',
    displayName: 'Kantale Divisional Hospital',
    nameTa: 'கண்டளை பிரிவு வைத்தியசாலை',
    officialCategory: OfficialCategory.DIVISIONAL_HOSPITAL_TYPE_A,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.EASTERN,
    district: 'Trincomalee',
    rdhsArea: 'Trincomalee',
    town: 'Kantale',
    address: { street: 'Hospital Road', city: 'Kantale', postalCode: '31100' },
    coordinates: null,
    telephoneNumbers: ['0262248261'],
    departments: ['OPD', 'Medicine', 'Maternity'],
    publicServices: ['OPD', 'Pharmacy'],
    emergencyAvailable: false,
    publishedBedStrength: 80,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // EASTERN PROVINCE — BATTICALOA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-BCL-001',
    officialName: 'Teaching Hospital Batticaloa',
    displayName: 'Batticaloa Teaching Hospital',
    nameTa: 'மட்டக்களப்பு போதனை வைத்தியசாலை',
    officialCategory: OfficialCategory.TEACHING_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.EASTERN,
    district: 'Batticaloa',
    rdhsArea: 'Batticaloa',
    town: 'Batticaloa',
    address: { street: 'Hospital Road', city: 'Batticaloa', postalCode: '30000' },
    coordinates: { lat: 7.7102, lng: 81.6924 },
    telephoneNumbers: ['0652222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics', 'ENT'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy', 'ICU'],
    emergencyAvailable: true,
    publishedBedStrength: 900,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-BCL-002',
    officialName: 'Base Hospital Type B — Kalmunai',
    displayName: 'Kalmunai Base Hospital',
    nameTa: 'கல்முனை அடிப்படை வைத்தியசாலை',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_B,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.EASTERN,
    district: 'Batticaloa',
    rdhsArea: 'Batticaloa',
    town: 'Kalmunai',
    address: { street: 'Hospital Road', city: 'Kalmunai', postalCode: '32300' },
    coordinates: null,
    telephoneNumbers: ['0672222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Maternity'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 195,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // EASTERN PROVINCE — AMPARA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-AMP-001',
    officialName: 'District General Hospital Ampara',
    displayName: 'Ampara District General Hospital',
    nameTa: 'அம்பாறை மாவட்ட பொது வைத்தியசாலை',
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.EASTERN,
    district: 'Ampara',
    rdhsArea: 'Ampara',
    town: 'Ampara',
    address: { street: 'Hospital Road', city: 'Ampara', postalCode: '32000' },
    coordinates: { lat: 7.2912, lng: 81.6747 },
    telephoneNumbers: ['0632222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 370,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // NORTH WESTERN PROVINCE — KURUNEGALA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-KGL-001',
    officialName: 'Teaching Hospital Kurunegala',
    displayName: 'Kurunegala Teaching Hospital',
    nameSi: 'කුරුණෑගල ශික්ෂණ රෝහල',
    alternativeNames: ['Kurunegala General Hospital'],
    officialCategory: OfficialCategory.TEACHING_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.NORTH_WESTERN,
    district: 'Kurunegala',
    rdhsArea: 'Kurunegala',
    town: 'Kurunegala',
    address: { street: 'Hospital Road', city: 'Kurunegala', postalCode: '60000' },
    coordinates: { lat: 7.4863, lng: 80.3623 },
    telephoneNumbers: ['0372222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics', 'Cardiology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy', 'ICU'],
    emergencyAvailable: true,
    publishedBedStrength: 1340,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-KGL-002',
    officialName: 'Base Hospital Type B — Kuliyapitiya',
    displayName: 'Kuliyapitiya Base Hospital',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_B,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.NORTH_WESTERN,
    district: 'Kurunegala',
    rdhsArea: 'Kurunegala',
    town: 'Kuliyapitiya',
    address: { street: 'Hospital Road', city: 'Kuliyapitiya', postalCode: '60200' },
    coordinates: null,
    telephoneNumbers: ['0372283261'],
    departments: ['Medicine', 'Surgery', 'Maternity'],
    publicServices: ['Emergency', 'OPD', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 200,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // NORTH WESTERN PROVINCE — PUTTALAM DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-PTL-001',
    officialName: 'District General Hospital Puttalam',
    displayName: 'Puttalam District General Hospital',
    nameSi: 'පුත්තලම දිස්ත්‍රික් මහ රෝහල',
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.NORTH_WESTERN,
    district: 'Puttalam',
    rdhsArea: 'Puttalam',
    town: 'Puttalam',
    address: { street: 'Hospital Road', city: 'Puttalam', postalCode: '61300' },
    coordinates: { lat: 8.0362, lng: 79.8283 },
    telephoneNumbers: ['0322222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 310,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // NORTH CENTRAL PROVINCE — ANURADHAPURA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-AND-001',
    officialName: 'Teaching Hospital Anuradhapura',
    displayName: 'Anuradhapura Teaching Hospital',
    nameSi: 'අනුරාධපුර ශික්ෂණ රෝහල',
    alternativeNames: ['Anuradhapura General Hospital'],
    officialCategory: OfficialCategory.TEACHING_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.NORTH_CENTRAL,
    district: 'Anuradhapura',
    rdhsArea: 'Anuradhapura',
    town: 'Anuradhapura',
    address: { street: 'Maithripala Senanayake Mawatha', city: 'Anuradhapura', postalCode: '50000' },
    coordinates: { lat: 8.3114, lng: 80.4037 },
    telephoneNumbers: ['0252222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics', 'Neurology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy', 'Blood Bank', 'ICU'],
    emergencyAvailable: true,
    publishedBedStrength: 1140,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-AND-002',
    officialName: 'Base Hospital Type A — Kekirawa',
    displayName: 'Kekirawa Base Hospital',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_A,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.NORTH_CENTRAL,
    district: 'Anuradhapura',
    rdhsArea: 'Anuradhapura',
    town: 'Kekirawa',
    address: { street: 'Hospital Road', city: 'Kekirawa', postalCode: '50500' },
    coordinates: null,
    telephoneNumbers: ['0252264261'],
    departments: ['Medicine', 'Surgery', 'Maternity'],
    publicServices: ['OPD', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 170,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // NORTH CENTRAL PROVINCE — POLONNARUWA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-POL-001',
    officialName: 'District General Hospital Polonnaruwa',
    displayName: 'Polonnaruwa District General Hospital',
    nameSi: 'පොළොන්නරුව දිස්ත්‍රික් මහ රෝහල',
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.NORTH_CENTRAL,
    district: 'Polonnaruwa',
    rdhsArea: 'Polonnaruwa',
    town: 'Polonnaruwa',
    address: { street: 'Hospital Road', city: 'Polonnaruwa', postalCode: '51000' },
    coordinates: { lat: 7.9403, lng: 81.0188 },
    telephoneNumbers: ['0272222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 448,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // UVA PROVINCE — BADULLA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-BDL-001',
    officialName: 'District General Hospital Badulla',
    displayName: 'Badulla District General Hospital',
    nameSi: 'බදුල්ල දිස්ත්‍රික් මහ රෝහල',
    alternativeNames: ['Badulla General Hospital'],
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.UVA,
    district: 'Badulla',
    rdhsArea: 'Badulla',
    town: 'Badulla',
    address: { street: 'Hospital Road', city: 'Badulla', postalCode: '90000' },
    coordinates: { lat: 6.9934, lng: 81.0550 },
    telephoneNumbers: ['0552222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 562,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-BDL-002',
    officialName: 'Base Hospital Type B — Bandarawela',
    displayName: 'Bandarawela Base Hospital',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_B,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.UVA,
    district: 'Badulla',
    rdhsArea: 'Badulla',
    town: 'Bandarawela',
    address: { street: 'Hospital Road', city: 'Bandarawela', postalCode: '90100' },
    coordinates: null,
    telephoneNumbers: ['0572222261'],
    departments: ['Medicine', 'Surgery', 'Maternity'],
    publicServices: ['Emergency', 'OPD', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 250,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // UVA PROVINCE — MONARAGALA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-MRG-001',
    officialName: 'District General Hospital Monaragala',
    displayName: 'Monaragala District General Hospital',
    nameSi: 'මොනරාගල දිස්ත්‍රික් මහ රෝහල',
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.UVA,
    district: 'Monaragala',
    rdhsArea: 'Monaragala',
    town: 'Monaragala',
    address: { street: 'Hospital Road', city: 'Monaragala', postalCode: '91000' },
    coordinates: { lat: 6.8728, lng: 81.3507 },
    telephoneNumbers: ['0552276261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Maternity'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 252,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // SABARAGAMUWA PROVINCE — RATNAPURA DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-RTP-001',
    officialName: 'District General Hospital Ratnapura',
    displayName: 'Ratnapura District General Hospital',
    nameSi: 'රත්නපුර දිස්ත්‍රික් මහ රෝහල',
    alternativeNames: ['Ratnapura General Hospital'],
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.SABARAGAMUWA,
    district: 'Ratnapura',
    rdhsArea: 'Ratnapura',
    town: 'Ratnapura',
    address: { street: 'Hospital Road', city: 'Ratnapura', postalCode: '70000' },
    coordinates: { lat: 6.6828, lng: 80.4009 },
    telephoneNumbers: ['0452222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology', 'Orthopaedics'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 680,
    publishedBedReportingYear: 2023,
  },
  {
    facilityCode: 'LKH-RTP-002',
    officialName: 'Base Hospital Type B — Embilipitiya',
    displayName: 'Embilipitiya Base Hospital',
    officialCategory: OfficialCategory.BASE_HOSPITAL_TYPE_B,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.SABARAGAMUWA,
    district: 'Ratnapura',
    rdhsArea: 'Ratnapura',
    town: 'Embilipitiya',
    address: { street: 'Hospital Road', city: 'Embilipitiya', postalCode: '70140' },
    coordinates: null,
    telephoneNumbers: ['0472222261'],
    departments: ['Medicine', 'Surgery', 'Maternity'],
    publicServices: ['Emergency', 'OPD', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 200,
    publishedBedReportingYear: 2023,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // SABARAGAMUWA PROVINCE — KEGALLE DISTRICT
  // ══════════════════════════════════════════════════════════════════════════
  {
    facilityCode: 'LKH-KEG-001',
    officialName: 'District General Hospital Kegalle',
    displayName: 'Kegalle District General Hospital',
    nameSi: 'කෑගල්ල දිස්ත්‍රික් මහ රෝහල',
    alternativeNames: ['Kegalle General Hospital'],
    officialCategory: OfficialCategory.DISTRICT_GENERAL_HOSPITAL,
    ownershipType: OwnershipType.MINISTRY_OF_HEALTH_LINE,
    province: SriLankaRegion.SABARAGAMUWA,
    district: 'Kegalle',
    rdhsArea: 'Kegalle',
    town: 'Kegalle',
    address: { street: 'Hospital Road', city: 'Kegalle', postalCode: '71000' },
    coordinates: { lat: 7.2513, lng: 80.3464 },
    telephoneNumbers: ['0352222261'],
    departments: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics & Gynaecology'],
    publicServices: ['Emergency', 'OPD', 'Laboratory', 'Pharmacy'],
    emergencyAvailable: true,
    publishedBedStrength: 380,
    publishedBedReportingYear: 2023,
  },
];

// ── Helpers ────────────────────────────────────────────────────────────────────

/** Returns the unique set of districts represented in the seed data */
export const getRepresentedDistricts = (): Set<string> =>
  new Set(HOSPITAL_SEED_DATA.map((h) => h.district));

/** Checks that all 25 Sri Lankan districts are represented */
export const ALL_25_DISTRICTS = [
  'Colombo', 'Gampaha', 'Kalutara',
  'Kandy', 'Matale', 'Nuwara Eliya',
  'Galle', 'Matara', 'Hambantota',
  'Jaffna', 'Kilinochchi', 'Mannar', 'Mullaitivu', 'Vavuniya',
  'Trincomalee', 'Batticaloa', 'Ampara',
  'Kurunegala', 'Puttalam',
  'Anuradhapura', 'Polonnaruwa',
  'Badulla', 'Monaragala',
  'Ratnapura', 'Kegalle',
];

export const getMissingDistricts = (): string[] => {
  const represented = getRepresentedDistricts();
  return ALL_25_DISTRICTS.filter((d) => !represented.has(d));
};
